from pygame import event, USEREVENT

ABOUT = USEREVENT + 1
MAIN_MENU = USEREVENT + 2
PLAY = USEREVENT + 3
HELP = USEREVENT + 4
RESUME = USEREVENT + 5
EXIT = USEREVENT + 6
NEXT_DIALOG_SECTION = USEREVENT + 7
GO_TO_LV_SELECTION = USEREVENT + 8
INTRODUCTION_DIALOGUE = USEREVENT + 9
NEXT_DLG_LINE = USEREVENT + 10
PRELOAD_SCREEN = USEREVENT + 11
